apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::588358566138:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IJR588HM816M
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::588358566138:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-10T12:12:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1485"
  uid: 71b13c8b-9c1f-4b17-b578-a2d40e45727c
